version: '3'
services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    user: root

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test_exam
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: hunghn2001
      MYSQL_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - '9000:80' # Nginx lắng nghe trên cổng 80
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app